(cl:in-package ds_nav_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DS_HEADER-VAL
          DS_HEADER
          LAT-VAL
          LAT
          LON-VAL
          LON
          NORTHING-VAL
          NORTHING
          EASTING-VAL
          EASTING
          DOWN-VAL
          DOWN
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          HEADING-VAL
          HEADING
          SURGE_U-VAL
          SURGE_U
          SWAY_V-VAL
          SWAY_V
          HEAVE_W-VAL
          HEAVE_W
          P-VAL
          P
          Q-VAL
          Q
          R-VAL
          R
          ORIENTATION-VAL
          ORIENTATION
))