// Generated by gencpp from file ds_sensor_msgs/NortekVectorSystem.msg
// DO NOT EDIT!


#ifndef DS_SENSOR_MSGS_MESSAGE_NORTEKVECTORSYSTEM_H
#define DS_SENSOR_MSGS_MESSAGE_NORTEKVECTORSYSTEM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ds_core_msgs/DsHeader.h>

namespace ds_sensor_msgs
{
template <class ContainerAllocator>
struct NortekVectorSystem_
{
  typedef NortekVectorSystem_<ContainerAllocator> Type;

  NortekVectorSystem_()
    : header()
    , ds_header()
    , clk()
    , battery(0.0)
    , sound_speed(0.0)
    , heading(0.0)
    , pitch(0.0)
    , roll(0.0)
    , temperature(0.0)
    , error(0)
    , status(0)
    , analog_input(0)  {
    }
  NortekVectorSystem_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ds_header(_alloc)
    , clk()
    , battery(0.0)
    , sound_speed(0.0)
    , heading(0.0)
    , pitch(0.0)
    , roll(0.0)
    , temperature(0.0)
    , error(0)
    , status(0)
    , analog_input(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::ds_core_msgs::DsHeader_<ContainerAllocator>  _ds_header_type;
  _ds_header_type ds_header;

   typedef ros::Time _clk_type;
  _clk_type clk;

   typedef double _battery_type;
  _battery_type battery;

   typedef double _sound_speed_type;
  _sound_speed_type sound_speed;

   typedef double _heading_type;
  _heading_type heading;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _temperature_type;
  _temperature_type temperature;

   typedef uint8_t _error_type;
  _error_type error;

   typedef uint8_t _status_type;
  _status_type status;

   typedef uint16_t _analog_input_type;
  _analog_input_type analog_input;





  typedef boost::shared_ptr< ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator> const> ConstPtr;

}; // struct NortekVectorSystem_

typedef ::ds_sensor_msgs::NortekVectorSystem_<std::allocator<void> > NortekVectorSystem;

typedef boost::shared_ptr< ::ds_sensor_msgs::NortekVectorSystem > NortekVectorSystemPtr;
typedef boost::shared_ptr< ::ds_sensor_msgs::NortekVectorSystem const> NortekVectorSystemConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator1> & lhs, const ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ds_header == rhs.ds_header &&
    lhs.clk == rhs.clk &&
    lhs.battery == rhs.battery &&
    lhs.sound_speed == rhs.sound_speed &&
    lhs.heading == rhs.heading &&
    lhs.pitch == rhs.pitch &&
    lhs.roll == rhs.roll &&
    lhs.temperature == rhs.temperature &&
    lhs.error == rhs.error &&
    lhs.status == rhs.status &&
    lhs.analog_input == rhs.analog_input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator1> & lhs, const ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ds_sensor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6935dfa6126b055c54943a7af546858";
  }

  static const char* value(const ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6935dfa6126b055ULL;
  static const uint64_t static_value2 = 0xc54943a7af546858ULL;
};

template<class ContainerAllocator>
struct DataType< ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ds_sensor_msgs/NortekVectorSystem";
  }

  static const char* value(const ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The standard 2-part DsHeader block\n"
"# This allows both a standard ROS header and DS-specific header blocks\n"
"# See HEADERS.md in ds_core_msgs for details\n"
"std_msgs/Header header\n"
"ds_core_msgs/DsHeader ds_header\n"
"\n"
"#####################################################################\n"
"# Raw data\n"
"\n"
"time clk\n"
"float64 battery #V\n"
"float64 sound_speed #m/s\n"
"float64 heading #deg\n"
"float64 pitch #deg\n"
"float64 roll #deg\n"
"float64 temperature #degC\n"
"uint8 error\n"
"uint8 status\n"
"uint16 analog_input\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ds_core_msgs/DsHeader\n"
"# This is half our standard header for ds_msgs; see\n"
"# HEADERS.md for details\n"
"\n"
"# This header should ALWAYS be paired with a std_msgs/Header\n"
"# and should ALWAYS reference HEADERS.md.  If you're looking at this\n"
"# file to add headers to a type, you probably want to copy/paste\n"
"# the following block:\n"
"#\n"
"#     # The standard 2-part DsHeader block\n"
"#     # This allows both a standard ROS header and DS-specific header blocks\n"
"#     # See HEADERS.md in ds_core_msgs for details\n"
"#     std_msgs/Header header\n"
"#     ds_core_msgs/DsHeader ds_header\n"
"#\n"
"\n"
"# Time data was received or sent out (i/o time)\n"
"time io_time\n"
"\n"
"# Sensor source UUID\n"
"uint8[16] source_uuid\n"
"\n"
;
  }

  static const char* value(const ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ds_header);
      stream.next(m.clk);
      stream.next(m.battery);
      stream.next(m.sound_speed);
      stream.next(m.heading);
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.temperature);
      stream.next(m.error);
      stream.next(m.status);
      stream.next(m.analog_input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NortekVectorSystem_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ds_sensor_msgs::NortekVectorSystem_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ds_header: ";
    s << std::endl;
    Printer< ::ds_core_msgs::DsHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.ds_header);
    s << indent << "clk: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.clk);
    s << indent << "battery: ";
    Printer<double>::stream(s, indent + "  ", v.battery);
    s << indent << "sound_speed: ";
    Printer<double>::stream(s, indent + "  ", v.sound_speed);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "temperature: ";
    Printer<double>::stream(s, indent + "  ", v.temperature);
    s << indent << "error: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "analog_input: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.analog_input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DS_SENSOR_MSGS_MESSAGE_NORTEKVECTORSYSTEM_H
