(cl:defpackage ds_mx_msgs-srv
  (:use )
  (:export
   "MXUPDATESHAREDPARAMS"
   "<MXUPDATESHAREDPARAMS-REQUEST>"
   "MXUPDATESHAREDPARAMS-REQUEST"
   "<MXUPDATESHAREDPARAMS-RESPONSE>"
   "MXUPDATESHAREDPARAMS-RESPONSE"
  ))

