(cl:defpackage ds_nav_msgs-srv
  (:use )
  (:export
   "REJPOLICYCMD"
   "<REJPOLICYCMD-REQUEST>"
   "REJPOLICYCMD-REQUEST"
   "<REJPOLICYCMD-RESPONSE>"
   "REJPOLICYCMD-RESPONSE"
   "RESETDVL"
   "<RESETDVL-REQUEST>"
   "RESETDVL-REQUEST"
   "<RESETDVL-RESPONSE>"
   "RESETDVL-RESPONSE"
   "ZUPTCMD"
   "<ZUPTCMD-REQUEST>"
   "ZUPTCMD-REQUEST"
   "<ZUPTCMD-RESPONSE>"
   "ZUPTCMD-RESPONSE"
  ))

