(cl:in-package ds_sensor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DS_HEADER-VAL
          DS_HEADER
          DVL_TYPE-VAL
          DVL_TYPE
          ALTITUDE_SUM-VAL
          ALTITUDE_SUM
          SPEED_GND-VAL
          SPEED_GND
          COURSE_GND-VAL
          COURSE_GND
          GOOD_BEAMS-VAL
          GOOD_BEAMS
          DVL_TIME-VAL
          DVL_TIME
          VERSION-VAL
          VERSION
          OFFSETOFDATA-VAL
          OFFSETOFDATA
          SERIALNUMBER-VAL
          SERIALNUMBER
          YEAR-VAL
          YEAR
          MONTH-VAL
          MONTH
          DAY-VAL
          DAY
          HOUR-VAL
          HOUR
          MINUTE-VAL
          MINUTE
          SECONDS-VAL
          SECONDS
          MICROSECONDS-VAL
          MICROSECONDS
          NBEAMS-VAL
          NBEAMS
          ERROR-VAL
          ERROR
          STATUS-VAL
          STATUS
          SPEED_SOUND-VAL
          SPEED_SOUND
          TEMPERATURE-VAL
          TEMPERATURE
          PRESSURE-VAL
          PRESSURE
          VELBEAM-VAL
          VELBEAM
          DISTBEAM-VAL
          DISTBEAM
          FOMBEAM-VAL
          FOMBEAM
          TIMEDIFF1BEAM-VAL
          TIMEDIFF1BEAM
          TIMEDIFF2BEAM-VAL
          TIMEDIFF2BEAM
          TIMEVELESTBEAM-VAL
          TIMEVELESTBEAM
          VELX-VAL
          VELX
          VELY-VAL
          VELY
          VELZ1-VAL
          VELZ1
          VELZ2-VAL
          VELZ2
          FOMX-VAL
          FOMX
          FOMY-VAL
          FOMY
          FOMZ1-VAL
          FOMZ1
          FOMZ2-VAL
          FOMZ2
          TIMEDIFF1X-VAL
          TIMEDIFF1X
          TIMEDIFF1Y-VAL
          TIMEDIFF1Y
          TIMEDIFF1Z1-VAL
          TIMEDIFF1Z1
          TIMEDIFF1Z2-VAL
          TIMEDIFF1Z2
          TIMEDIFF2X-VAL
          TIMEDIFF2X
          TIMEDIFF2Y-VAL
          TIMEDIFF2Y
          TIMEDIFF2Z1-VAL
          TIMEDIFF2Z1
          TIMEDIFF2Z2-VAL
          TIMEDIFF2Z2
          TIMEVELESTX-VAL
          TIMEVELESTX
          TIMEVELESTY-VAL
          TIMEVELESTY
          TIMEVELESTZ1-VAL
          TIMEVELESTZ1
          TIMEVELESTZ2-VAL
          TIMEVELESTZ2
))