(cl:in-package ds_sensor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DS_HEADER-VAL
          DS_HEADER
          HEADING_DEG-VAL
          HEADING_DEG
          PITCH_DEG-VAL
          PITCH_DEG
          ROLL_DEG-VAL
          ROLL_DEG
          LATITUDE_DEG-VAL
          LATITUDE_DEG
          LONGITUDE_DEG-VAL
          LONGITUDE_DEG
          ALTITUDE_M-VAL
          ALTITUDE_M
          EAST_SPEED_M_S-VAL
          EAST_SPEED_M_S
          NORTH_SPEED_M_S-VAL
          NORTH_SPEED_M_S
          UP_SPEED_M_S-VAL
          UP_SPEED_M_S
          LAT_UTM_ZONE-VAL
          LAT_UTM_ZONE
          LON_UTM_ZONE-VAL
          LON_UTM_ZONE
          UTM_EAST_POS_M-VAL
          UTM_EAST_POS_M
          UTM_NORTH_POS_M-VAL
          UTM_NORTH_POS_M
          UTM_ALTITUDE_M-VAL
          UTM_ALTITUDE_M
          SURGE_M-VAL
          SURGE_M
          SWAY_M-VAL
          SWAY_M
          HEAVE_M-VAL
          HEAVE_M
          LAT_STD_DEV_M-VAL
          LAT_STD_DEV_M
          LON_STD_DEV_M-VAL
          LON_STD_DEV_M
          ALTITUDE_STD_DEV_M-VAL
          ALTITUDE_STD_DEV_M
          EAST_SPEED_STD_DEV_M_S-VAL
          EAST_SPEED_STD_DEV_M_S
          NORTH_SPEED_STD_DEV_M_S-VAL
          NORTH_SPEED_STD_DEV_M_S
          UP_SPEED_STD_DEV_M_S-VAL
          UP_SPEED_STD_DEV_M_S
          TIME_POS-VAL
          TIME_POS
          ALGORITHM_STATUS_LSB-VAL
          ALGORITHM_STATUS_LSB
          ALGORITHM_STATUS_MSB-VAL
          ALGORITHM_STATUS_MSB
          SYSTEM_STATUS_LSB-VAL
          SYSTEM_STATUS_LSB
          SYSTEM_STATUS_MSB-VAL
          SYSTEM_STATUS_MSB
          USER_STATUS-VAL
          USER_STATUS
))