(cl:in-package ds_sensor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DS_HEADER-VAL
          DS_HEADER
          DVL_TIME-VAL
          DVL_TIME
          VELOCITY-VAL
          VELOCITY
          VELOCITY_COVAR-VAL
          VELOCITY_COVAR
          ALTITUDE-VAL
          ALTITUDE
          COURSE_GND-VAL
          COURSE_GND
          SPEED_GND-VAL
          SPEED_GND
          NUM_GOOD_BEAMS-VAL
          NUM_GOOD_BEAMS
          SPEED_SOUND-VAL
          SPEED_SOUND
          BEAM_UNIT_VEC-VAL
          BEAM_UNIT_VEC
          RANGE-VAL
          RANGE
          RANGE_COVAR-VAL
          RANGE_COVAR
          BEAM_QUALITY-VAL
          BEAM_QUALITY
          RAW_VELOCITY-VAL
          RAW_VELOCITY
          RAW_VELOCITY_COVAR-VAL
          RAW_VELOCITY_COVAR
          VELOCITY_MODE-VAL
          VELOCITY_MODE
          COORDINATE_MODE-VAL
          COORDINATE_MODE
          DVL_TYPE-VAL
          DVL_TYPE
))