(cl:in-package ds_sensor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DS_HEADER-VAL
          DS_HEADER
          DVL_TYPE-VAL
          DVL_TYPE
          ALTITUDE_SUM-VAL
          ALTITUDE_SUM
          SPEED_GND-VAL
          SPEED_GND
          COURSE_GND-VAL
          COURSE_GND
          GOOD_BEAMS-VAL
          GOOD_BEAMS
          DVL_TIME-VAL
          DVL_TIME
          CONFIG-VAL
          CONFIG
          COORD_MODE-VAL
          COORD_MODE
          VELOCITY-VAL
          VELOCITY
          RANGE-VAL
          RANGE
          BOTTOM_STATUS-VAL
          BOTTOM_STATUS
          LAYER_VELOCITY-VAL
          LAYER_VELOCITY
          REF_LAYER_START-VAL
          REF_LAYER_START
          REF_LAYER_END-VAL
          REF_LAYER_END
          REF_LAYER_STATUS-VAL
          REF_LAYER_STATUS
          TOFP_HOUR-VAL
          TOFP_HOUR
          TOFP_MINUTE-VAL
          TOFP_MINUTE
          TOFP_SECOND-VAL
          TOFP_SECOND
          TOFP_HUNDRETHS-VAL
          TOFP_HUNDRETHS
          BIT_RESULTS-VAL
          BIT_RESULTS
          SOUND_VEL-VAL
          SOUND_VEL
          TEMPERATURE-VAL
          TEMPERATURE
          SALINITY-VAL
          SALINITY
          DEPTH-VAL
          DEPTH
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          HEADING-VAL
          HEADING
          BT_DISTANCE_EAST-VAL
          BT_DISTANCE_EAST
          BT_DISTANCE_NORTH-VAL
          BT_DISTANCE_NORTH
          BT_DISTANCE_UP-VAL
          BT_DISTANCE_UP
          BT_DISTANCE_ERROR-VAL
          BT_DISTANCE_ERROR
          REF_DISTANCE_EAST-VAL
          REF_DISTANCE_EAST
          REF_DISTANCE_NORTH-VAL
          REF_DISTANCE_NORTH
          REF_DISTANCE_UP-VAL
          REF_DISTANCE_UP
          REF_DISTANCE_ERROR-VAL
          REF_DISTANCE_ERROR
))