(cl:defpackage ds_core_msgs-srv
  (:use )
  (:export
   "IOSMCOMMAND"
   "<IOSMCOMMAND-REQUEST>"
   "IOSMCOMMAND-REQUEST"
   "<IOSMCOMMAND-RESPONSE>"
   "IOSMCOMMAND-RESPONSE"
   "STRINGCMD"
   "<STRINGCMD-REQUEST>"
   "STRINGCMD-REQUEST"
   "<STRINGCMD-RESPONSE>"
   "STRINGCMD-RESPONSE"
   "VOIDCMD"
   "<VOIDCMD-REQUEST>"
   "VOIDCMD-REQUEST"
   "<VOIDCMD-RESPONSE>"
   "VOIDCMD-RESPONSE"
  ))

