# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ds_sensor_msgs/UbloxSatellites.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ds_core_msgs.msg
import ds_sensor_msgs.msg
import genpy
import std_msgs.msg

class UbloxSatellites(genpy.Message):
  _md5sum = "ea82da18f2e861682f67aae821fdd311"
  _type = "ds_sensor_msgs/UbloxSatellites"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# The standard 2-part DsHeader block
# This allows both a standard ROS header and DS-specific header blocks
# See HEADERS.md in ds_core_msgs for details
std_msgs/Header header
ds_core_msgs/DsHeader ds_header

# GPS time of this message
uint32 time_of_week

UbloxSatellite[] sats
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: ds_core_msgs/DsHeader
# This is half our standard header for ds_msgs; see
# HEADERS.md for details

# This header should ALWAYS be paired with a std_msgs/Header
# and should ALWAYS reference HEADERS.md.  If you're looking at this
# file to add headers to a type, you probably want to copy/paste
# the following block:
#
#     # The standard 2-part DsHeader block
#     # This allows both a standard ROS header and DS-specific header blocks
#     # See HEADERS.md in ds_core_msgs for details
#     std_msgs/Header header
#     ds_core_msgs/DsHeader ds_header
#

# Time data was received or sent out (i/o time)
time io_time

# Sensor source UUID
uint8[16] source_uuid


================================================================================
MSG: ds_sensor_msgs/UbloxSatellite
# A string identifying which GNSS system is in use (e.g., GPS, BeiDou, GLONASS, etc)
string gnss_id

# The ID of the specific satellite that broadcast the signal.  Includes
# a letter indicating the service.  Example: GPS satellite #4 would be G4.
# IDs:
# G: GPS (US system)
# S: SBAS (Satellite Based Augmentation System, so WAAS, EGNOS, SDCM, GAGAN, etc)
# E: Galileo (European system)
# B: BeiDou (Chinese system)
# Q: QZSS (Japanese SBAS that also transmits GPS-style timing signals)
# R: GLONASS (Russian system)
string sat_id

# Carrier-to-noise-density ratio (dBHz)
float32 carrier_noise

# Pseudorange residual, in meters
float32 pseudorange_residual

# Satellite location, in degrees
float32 elevation
float32 azimuth

# Quality indicator
uint8 quality_indicator
uint8 QUALITY_NOSIGNAL = 0
uint8 QUALITY_SEARCHING = 1
uint8 QUALITY_ACQUIRED = 2
uint8 QUALITY_UNUSABLE = 3
uint8 QUALITY_CODELOCKED = 4
uint8 QUALITY_CODECARRIERTIME_LOCKED_5 = 5
uint8 QUALITY_CODECARRIERTIME_LOCKED_6 = 6
uint8 QUALITY_CODECARRIERTIME_LOCKED_7 = 7

# flags
uint8 health
uint8 HEALTH_UNKNOWN = 0
uint8 HEALTH_HEALTHY = 1
uint8 HEALTH_UNHEALTH = 2

bool differential_available
bool pseudorange_smoothed

uint8 oribt_source
uint8 ORBIT_SOURCE_NONE = 0
uint8 ORBIT_SOURCE_EPHEMERIS = 1
uint8 ORBIT_SOURCE_ALMANAC = 2
uint8 ORBIT_SOURCE_ASSISTNOW_OFFLINE = 3
uint8 ORBIT_SOURCE_ASSISTNOW_AUTONOMOUS = 4
uint8 ORBIT_SOURCE_OTHER5 = 5
uint8 ORBIT_SOURCE_OTHER6 = 6
uint8 ORBIT_SOURCE_OTHER7 = 7

bool ephAvail
bool almAvail
bool anoAvail
bool aopAvail
bool sbasCorrUsed
bool rtcmCorrUsed
bool slasCorrUsed
bool pseudorange_corrections_applied
bool carrier_range_corrections_applied
bool doppler_corrections_applied"""
  __slots__ = ['header','ds_header','time_of_week','sats']
  _slot_types = ['std_msgs/Header','ds_core_msgs/DsHeader','uint32','ds_sensor_msgs/UbloxSatellite[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ds_header,time_of_week,sats

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(UbloxSatellites, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ds_header is None:
        self.ds_header = ds_core_msgs.msg.DsHeader()
      if self.time_of_week is None:
        self.time_of_week = 0
      if self.sats is None:
        self.sats = []
    else:
      self.header = std_msgs.msg.Header()
      self.ds_header = ds_core_msgs.msg.DsHeader()
      self.time_of_week = 0
      self.sats = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.ds_header.io_time.secs, _x.ds_header.io_time.nsecs))
      _x = self.ds_header.source_uuid
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_16B().pack(*_x))
      else:
        buff.write(_get_struct_16s().pack(_x))
      _x = self.time_of_week
      buff.write(_get_struct_I().pack(_x))
      length = len(self.sats)
      buff.write(_struct_I.pack(length))
      for val1 in self.sats:
        _x = val1.gnss_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.sat_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_4f15B().pack(_x.carrier_noise, _x.pseudorange_residual, _x.elevation, _x.azimuth, _x.quality_indicator, _x.health, _x.differential_available, _x.pseudorange_smoothed, _x.oribt_source, _x.ephAvail, _x.almAvail, _x.anoAvail, _x.aopAvail, _x.sbasCorrUsed, _x.rtcmCorrUsed, _x.slasCorrUsed, _x.pseudorange_corrections_applied, _x.carrier_range_corrections_applied, _x.doppler_corrections_applied))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ds_header is None:
        self.ds_header = ds_core_msgs.msg.DsHeader()
      if self.sats is None:
        self.sats = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.ds_header.io_time.secs, _x.ds_header.io_time.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 16
      self.ds_header.source_uuid = str[start:end]
      start = end
      end += 4
      (self.time_of_week,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sats = []
      for i in range(0, length):
        val1 = ds_sensor_msgs.msg.UbloxSatellite()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.gnss_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.gnss_id = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.sat_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.sat_id = str[start:end]
        _x = val1
        start = end
        end += 31
        (_x.carrier_noise, _x.pseudorange_residual, _x.elevation, _x.azimuth, _x.quality_indicator, _x.health, _x.differential_available, _x.pseudorange_smoothed, _x.oribt_source, _x.ephAvail, _x.almAvail, _x.anoAvail, _x.aopAvail, _x.sbasCorrUsed, _x.rtcmCorrUsed, _x.slasCorrUsed, _x.pseudorange_corrections_applied, _x.carrier_range_corrections_applied, _x.doppler_corrections_applied,) = _get_struct_4f15B().unpack(str[start:end])
        val1.differential_available = bool(val1.differential_available)
        val1.pseudorange_smoothed = bool(val1.pseudorange_smoothed)
        val1.ephAvail = bool(val1.ephAvail)
        val1.almAvail = bool(val1.almAvail)
        val1.anoAvail = bool(val1.anoAvail)
        val1.aopAvail = bool(val1.aopAvail)
        val1.sbasCorrUsed = bool(val1.sbasCorrUsed)
        val1.rtcmCorrUsed = bool(val1.rtcmCorrUsed)
        val1.slasCorrUsed = bool(val1.slasCorrUsed)
        val1.pseudorange_corrections_applied = bool(val1.pseudorange_corrections_applied)
        val1.carrier_range_corrections_applied = bool(val1.carrier_range_corrections_applied)
        val1.doppler_corrections_applied = bool(val1.doppler_corrections_applied)
        self.sats.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.ds_header.io_time.secs, _x.ds_header.io_time.nsecs))
      _x = self.ds_header.source_uuid
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_16B().pack(*_x))
      else:
        buff.write(_get_struct_16s().pack(_x))
      _x = self.time_of_week
      buff.write(_get_struct_I().pack(_x))
      length = len(self.sats)
      buff.write(_struct_I.pack(length))
      for val1 in self.sats:
        _x = val1.gnss_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.sat_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_4f15B().pack(_x.carrier_noise, _x.pseudorange_residual, _x.elevation, _x.azimuth, _x.quality_indicator, _x.health, _x.differential_available, _x.pseudorange_smoothed, _x.oribt_source, _x.ephAvail, _x.almAvail, _x.anoAvail, _x.aopAvail, _x.sbasCorrUsed, _x.rtcmCorrUsed, _x.slasCorrUsed, _x.pseudorange_corrections_applied, _x.carrier_range_corrections_applied, _x.doppler_corrections_applied))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ds_header is None:
        self.ds_header = ds_core_msgs.msg.DsHeader()
      if self.sats is None:
        self.sats = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.ds_header.io_time.secs, _x.ds_header.io_time.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 16
      self.ds_header.source_uuid = str[start:end]
      start = end
      end += 4
      (self.time_of_week,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sats = []
      for i in range(0, length):
        val1 = ds_sensor_msgs.msg.UbloxSatellite()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.gnss_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.gnss_id = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.sat_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.sat_id = str[start:end]
        _x = val1
        start = end
        end += 31
        (_x.carrier_noise, _x.pseudorange_residual, _x.elevation, _x.azimuth, _x.quality_indicator, _x.health, _x.differential_available, _x.pseudorange_smoothed, _x.oribt_source, _x.ephAvail, _x.almAvail, _x.anoAvail, _x.aopAvail, _x.sbasCorrUsed, _x.rtcmCorrUsed, _x.slasCorrUsed, _x.pseudorange_corrections_applied, _x.carrier_range_corrections_applied, _x.doppler_corrections_applied,) = _get_struct_4f15B().unpack(str[start:end])
        val1.differential_available = bool(val1.differential_available)
        val1.pseudorange_smoothed = bool(val1.pseudorange_smoothed)
        val1.ephAvail = bool(val1.ephAvail)
        val1.almAvail = bool(val1.almAvail)
        val1.anoAvail = bool(val1.anoAvail)
        val1.aopAvail = bool(val1.aopAvail)
        val1.sbasCorrUsed = bool(val1.sbasCorrUsed)
        val1.rtcmCorrUsed = bool(val1.rtcmCorrUsed)
        val1.slasCorrUsed = bool(val1.slasCorrUsed)
        val1.pseudorange_corrections_applied = bool(val1.pseudorange_corrections_applied)
        val1.carrier_range_corrections_applied = bool(val1.carrier_range_corrections_applied)
        val1.doppler_corrections_applied = bool(val1.doppler_corrections_applied)
        self.sats.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_16B = None
def _get_struct_16B():
    global _struct_16B
    if _struct_16B is None:
        _struct_16B = struct.Struct("<16B")
    return _struct_16B
_struct_16s = None
def _get_struct_16s():
    global _struct_16s
    if _struct_16s is None:
        _struct_16s = struct.Struct("<16s")
    return _struct_16s
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4f15B = None
def _get_struct_4f15B():
    global _struct_4f15B
    if _struct_4f15B is None:
        _struct_4f15B = struct.Struct("<4f15B")
    return _struct_4f15B
