(cl:in-package ds_nmea_msgs-msg)
(cl:export '(TALKER-VAL
          TALKER
          TIMESTAMP-VAL
          TIMESTAMP
          LATITUDE-VAL
          LATITUDE
          LATITUDE_DIR-VAL
          LATITUDE_DIR
          LONGITUDE-VAL
          LONGITUDE
          LONGITUDE_DIR-VAL
          LONGITUDE_DIR
          FIX_QUALITY-VAL
          FIX_QUALITY
          NUM_SATELLITES-VAL
          NUM_SATELLITES
          HDOP-VAL
          HDOP
          ANTENNA_ALT-VAL
          ANTENNA_ALT
          ANTENNA_ALT_UNIT-VAL
          ANTENNA_ALT_UNIT
          GEOID_SEPARATION-VAL
          GEOID_SEPARATION
          GEOID_SEPARATION_UNIT-VAL
          GEOID_SEPARATION_UNIT
          DGPS_AGE-VAL
          DGPS_AGE
          DGPS_REF-VAL
          DGPS_REF
          CHECKSUM-VAL
          CHECKSUM
))