// Generated by gencpp from file dave_gazebo_ros_plugins/SetCurrentModel.msg
// DO NOT EDIT!


#ifndef DAVE_GAZEBO_ROS_PLUGINS_MESSAGE_SETCURRENTMODEL_H
#define DAVE_GAZEBO_ROS_PLUGINS_MESSAGE_SETCURRENTMODEL_H

#include <ros/service_traits.h>


#include <dave_gazebo_ros_plugins/SetCurrentModelRequest.h>
#include <dave_gazebo_ros_plugins/SetCurrentModelResponse.h>


namespace dave_gazebo_ros_plugins
{

struct SetCurrentModel
{

typedef SetCurrentModelRequest Request;
typedef SetCurrentModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCurrentModel
} // namespace dave_gazebo_ros_plugins


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dave_gazebo_ros_plugins::SetCurrentModel > {
  static const char* value()
  {
    return "97b431fd7a0d7100472976b98c315e14";
  }

  static const char* value(const ::dave_gazebo_ros_plugins::SetCurrentModel&) { return value(); }
};

template<>
struct DataType< ::dave_gazebo_ros_plugins::SetCurrentModel > {
  static const char* value()
  {
    return "dave_gazebo_ros_plugins/SetCurrentModel";
  }

  static const char* value(const ::dave_gazebo_ros_plugins::SetCurrentModel&) { return value(); }
};


// service_traits::MD5Sum< ::dave_gazebo_ros_plugins::SetCurrentModelRequest> should match
// service_traits::MD5Sum< ::dave_gazebo_ros_plugins::SetCurrentModel >
template<>
struct MD5Sum< ::dave_gazebo_ros_plugins::SetCurrentModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dave_gazebo_ros_plugins::SetCurrentModel >::value();
  }
  static const char* value(const ::dave_gazebo_ros_plugins::SetCurrentModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dave_gazebo_ros_plugins::SetCurrentModelRequest> should match
// service_traits::DataType< ::dave_gazebo_ros_plugins::SetCurrentModel >
template<>
struct DataType< ::dave_gazebo_ros_plugins::SetCurrentModelRequest>
{
  static const char* value()
  {
    return DataType< ::dave_gazebo_ros_plugins::SetCurrentModel >::value();
  }
  static const char* value(const ::dave_gazebo_ros_plugins::SetCurrentModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dave_gazebo_ros_plugins::SetCurrentModelResponse> should match
// service_traits::MD5Sum< ::dave_gazebo_ros_plugins::SetCurrentModel >
template<>
struct MD5Sum< ::dave_gazebo_ros_plugins::SetCurrentModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dave_gazebo_ros_plugins::SetCurrentModel >::value();
  }
  static const char* value(const ::dave_gazebo_ros_plugins::SetCurrentModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dave_gazebo_ros_plugins::SetCurrentModelResponse> should match
// service_traits::DataType< ::dave_gazebo_ros_plugins::SetCurrentModel >
template<>
struct DataType< ::dave_gazebo_ros_plugins::SetCurrentModelResponse>
{
  static const char* value()
  {
    return DataType< ::dave_gazebo_ros_plugins::SetCurrentModel >::value();
  }
  static const char* value(const ::dave_gazebo_ros_plugins::SetCurrentModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DAVE_GAZEBO_ROS_PLUGINS_MESSAGE_SETCURRENTMODEL_H
