(cl:in-package ds_hotel_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DS_HEADER-VAL
          DS_HEADER
          IDNUM-VAL
          IDNUM
          MEAS_VOLTS-VAL
          MEAS_VOLTS
          MEAS_AMPS-VAL
          MEAS_AMPS
          PROG_VOLTS-VAL
          PROG_VOLTS
          PROG_AMPS-VAL
          PROG_AMPS
          OUTPUT_ENABLE-VAL
          OUTPUT_ENABLE
          STATUS_GOOD-VAL
          STATUS_GOOD
          FRONTPANEL_LOCKED-VAL
          FRONTPANEL_LOCKED
          FAULT-VAL
          FAULT
          CONSTANT_VOLTAGE-VAL
          CONSTANT_VOLTAGE
          CONSTANT_CURRENT-VAL
          CONSTANT_CURRENT
          STATUS_MSG-VAL
          STATUS_MSG
))