(cl:in-package ds_hotel_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DS_HEADER-VAL
          DS_HEADER
          DEADHOUR-VAL
          DEADHOUR
          GOOD-VAL
          GOOD
          ADDRESS-VAL
          ADDRESS
          IDNUM-VAL
          IDNUM
          C-VAL
          C
          V-VAL
          V
          VALVE_CURRENT_LEVEL-VAL
          VALVE_CURRENT_LEVEL
          VALVE_RUN-VAL
          VALVE_RUN
          VALVE_OPEN-VAL
          VALVE_OPEN
          VALVE_BATTERY_SET_ON-VAL
          VALVE_BATTERY_SET_ON
          VALVE_BATTERY_SET_OFF-VAL
          VALVE_BATTERY_SET_OFF
          M-VAL
          M
          MOTOR_2_DROP-VAL
          MOTOR_2_DROP
          MOTOR_2_HOLD-VAL
          MOTOR_2_HOLD
          MOTOR_1_DROP-VAL
          MOTOR_1_DROP
          MOTOR_1_HOLD-VAL
          MOTOR_1_HOLD
          A-VAL
          A
          BURNWIRE_1_DRIVE-VAL
          BURNWIRE_1_DRIVE
          BURNWIRE_2_DRIVE-VAL
          BURNWIRE_2_DRIVE
          MOTOR_1_SECS-VAL
          MOTOR_1_SECS
          MOTOR_2_SECS-VAL
          MOTOR_2_SECS
          BURNWIRE_1_SECS-VAL
          BURNWIRE_1_SECS
          BURNWIRE_2_SECS-VAL
          BURNWIRE_2_SECS
          SHORT_DEADSECS-VAL
          SHORT_DEADSECS
          SHORT_DEADSECS_IDLE-VAL
          SHORT_DEADSECS_IDLE
          DEADSECS-VAL
          DEADSECS
          DD-VAL
          DD
))