(cl:in-package ds_actuator_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DS_HEADER-VAL
          DS_HEADER
          CMD-VAL
          CMD
          SPEED_LOOP_ENABLE_STATUS-VAL
          SPEED_LOOP_ENABLE_STATUS
          MINUTE_TAG-VAL
          MINUTE_TAG
          SECOND_TAG-VAL
          SECOND_TAG
          MICROSECOND_TICK_TAG-VAL
          MICROSECOND_TICK_TAG
          PROP_PWM-VAL
          PROP_PWM
          TACH_RPM-VAL
          TACH_RPM
          FAULT_STATUS-VAL
          FAULT_STATUS
          RESET_STATUS-VAL
          RESET_STATUS
          SPEED_LOOP_INTERVAL-VAL
          SPEED_LOOP_INTERVAL
          TACH_ERR_COUNT-VAL
          TACH_ERR_COUNT
          VOLTAGE_VOLTS-VAL
          VOLTAGE_VOLTS
          CURRENT_AMPS-VAL
          CURRENT_AMPS
))