(cl:defpackage ds_acomms_msgs-srv
  (:use )
  (:export
   "MODEMDATAREQUEST"
   "<MODEMDATAREQUEST-REQUEST>"
   "MODEMDATAREQUEST-REQUEST"
   "<MODEMDATAREQUEST-RESPONSE>"
   "MODEMDATAREQUEST-RESPONSE"
  ))

