(cl:in-package ds_multibeam_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DS_HEADER-VAL
          DS_HEADER
          SND_VELOCITY-VAL
          SND_VELOCITY
          SAMPLE_RATE-VAL
          SAMPLE_RATE
          NUM_BEAMS-VAL
          NUM_BEAMS
          PING_NUM-VAL
          PING_NUM
          PERCENT_GOOD-VAL
          PERCENT_GOOD
          MAX_DEPTH-VAL
          MAX_DEPTH
          MIN_DEPTH-VAL
          MIN_DEPTH
          CENTER_DEPTH-VAL
          CENTER_DEPTH
          MAX_RANGE-VAL
          MAX_RANGE
          MIN_RANGE-VAL
          MIN_RANGE
          CENTER_RANGE-VAL
          CENTER_RANGE
          PING_TIME-VAL
          PING_TIME
          TIME_NET-VAL
          TIME_NET
          PING_RATE-VAL
          PING_RATE
          BATHY_DATATYPE-VAL
          BATHY_DATATYPE
          BEAM_DIST_MODE-VAL
          BEAM_DIST_MODE
          SONAR_MODE-VAL
          SONAR_MODE
          TX_ANGLE-VAL
          TX_ANGLE
          GAIN-VAL
          GAIN
          TX_FREQ-VAL
          TX_FREQ
          TX_BW-VAL
          TX_BW
          TX_LEN-VAL
          TX_LEN
          TX_VOLTAGE-VAL
          TX_VOLTAGE
          SWATH_DIR-VAL
          SWATH_DIR
          SWATH_OPEN-VAL
          SWATH_OPEN
          GATE_TILT-VAL
          GATE_TILT
          SAMPLE_NUM-VAL
          SAMPLE_NUM
          BEAM_DISTANCE-VAL
          BEAM_DISTANCE
          ANGLE-VAL
          ANGLE
          UPPER_GATE-VAL
          UPPER_GATE
          LOWER_GATE-VAL
          LOWER_GATE
          INTENSITY-VAL
          INTENSITY
          FLAGS-VAL
          FLAGS
          QUALITY_FLAG-VAL
          QUALITY_FLAG
          QUALITY_VAL-VAL
          QUALITY_VAL
))