(cl:in-package ds_multibeam_msgs-msg)
(cl:export '(SOUNDINGS_TOTAL-VAL
          SOUNDINGS_TOTAL
          SOUNDINGS_ACCEPTED-VAL
          SOUNDINGS_ACCEPTED
          SOUNDINGS_FLAGGED-VAL
          SOUNDINGS_FLAGGED
          SOUNDINGS_DROPPED-VAL
          SOUNDINGS_DROPPED
          CELL_SIZE-VAL
          CELL_SIZE
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          GRID_CELLS_USED-VAL
          GRID_CELLS_USED
          GRID_CELLS_TOTAL-VAL
          GRID_CELLS_TOTAL
          GRID_MEMORY_MB-VAL
          GRID_MEMORY_MB
          GRID_MEMORY_LIMIT_MB-VAL
          GRID_MEMORY_LIMIT_MB
          GRID_ORIGIN_EASTING-VAL
          GRID_ORIGIN_EASTING
          GRID_ORIGIN_NORTHING-VAL
          GRID_ORIGIN_NORTHING
))