(cl:in-package ds_multibeam_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DS_HEADER-VAL
          DS_HEADER
          SND_VELOCITY-VAL
          SND_VELOCITY
          SAMPLE_RATE-VAL
          SAMPLE_RATE
          NUM_BEAMS-VAL
          NUM_BEAMS
          SAMPLE_NUM-VAL
          SAMPLE_NUM
          PING_TIME-VAL
          PING_TIME
          DTYPE-VAL
          DTYPE
          T0-VAL
          T0
          GAIN-VAL
          GAIN
          SWATH_DIR-VAL
          SWATH_DIR
          SWATH_OPEN-VAL
          SWATH_OPEN
          TX_FREQ-VAL
          TX_FREQ
          TX_BW-VAL
          TX_BW
          TX_LEN-VAL
          TX_LEN
          TX_AMP-VAL
          TX_AMP
          PING_RATE-VAL
          PING_RATE
          PING_NUM-VAL
          PING_NUM
          TIME_NET-VAL
          TIME_NET
          BEAMS-VAL
          BEAMS
          VGA_T1-VAL
          VGA_T1
          VGA_G1-VAL
          VGA_G1
          VGA_T2-VAL
          VGA_T2
          VGA_G2-VAL
          VGA_G2
          TX_ANGLE-VAL
          TX_ANGLE
          TX_VOLTAGE-VAL
          TX_VOLTAGE
          BEAM_DIST_MODE-VAL
          BEAM_DIST_MODE
          SONAR_MODE-VAL
          SONAR_MODE
          GATE_TILT-VAL
          GATE_TILT
          PIXEL_DATA-VAL
          PIXEL_DATA
          BEAM_DIR-VAL
          BEAM_DIR
          BEAM_DISTANCE-VAL
          BEAM_DISTANCE
))