(cl:in-package ds_ocomms_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DS_HEADER-VAL
          DS_HEADER
          IP_ADDR-VAL
          IP_ADDR
          NETMASK-VAL
          NETMASK
          BRDCST-VAL
          BRDCST
          DFLTGW-VAL
          DFLTGW
          DFLTIP-VAL
          DFLTIP
          DFLMAC-VAL
          DFLMAC
          DFLPRT-VAL
          DFLPRT
          LARIPA-VAL
          LARIPA
          LARMAC-VAL
          LARMAC
          LARPRT-VAL
          LARPRT
          LFPIPA-VAL
          LFPIPA
          LFPMAC-VAL
          LFPMAC
          LFPPRT-VAL
          LFPPRT
          REMIPA-VAL
          REMIPA
          RARIPA-VAL
          RARIPA
          RARMAC-VAL
          RARMAC
          RSUBNT-VAL
          RSUBNT
          BRDGEN-VAL
          BRDGEN
          BRDGIP-VAL
          BRDGIP
          GUIIPA-VAL
          GUIIPA
          FPG3VR-VAL
          FPG3VR
          FPG6VR-VAL
          FPG6VR
          SOFTVR-VAL
          SOFTVR
          REBOOT-VAL
          REBOOT
          DFMODE-VAL
          DFMODE
          MASTER_SLAVEN-VAL
          MASTER_SLAVEN
          LOGENA-VAL
          LOGENA
          ACSTEN-VAL
          ACSTEN
          ACSTMAST_SLAVEN-VAL
          ACSTMAST_SLAVEN
          ACSTMFG-VAL
          ACSTMFG
          LAMDID-VAL
          LAMDID
          RAMDID-VAL
          RAMDID
          SENSITIVITY_CTRL-VAL
          SENSITIVITY_CTRL
          LRHALN-VAL
          LRHALN
          STATUS1HZ_ENABLE-VAL
          STATUS1HZ_ENABLE
))