(cl:in-package ds_ocomms_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DS_HEADER-VAL
          DS_HEADER
          LINK_STATE-VAL
          LINK_STATE
          TIMESTAMP_DATE-VAL
          TIMESTAMP_DATE
          TIMESTAMP_TIME-VAL
          TIMESTAMP_TIME
          TDMA_MODE-VAL
          TDMA_MODE
          CARRIER_RATE-VAL
          CARRIER_RATE
          TX_RATE-VAL
          TX_RATE
          RX_RATE-VAL
          RX_RATE
          FEC_CORRECTS-VAL
          FEC_CORRECTS
          FEC_FAILURE-VAL
          FEC_FAILURE
          DEADLINK_TIMER-VAL
          DEADLINK_TIMER
          CHECKSUM_FAILURES-VAL
          CHECKSUM_FAILURES
          TX_KBPS-VAL
          TX_KBPS
          RX_KBPS-VAL
          RX_KBPS
          CORR_VAL-VAL
          CORR_VAL
          HV_DAC-VAL
          HV_DAC
          DC_ADC-VAL
          DC_ADC
          AC_ADC-VAL
          AC_ADC
          BACKSCATTER_ADC-VAL
          BACKSCATTER_ADC
          GATING_MODE-VAL
          GATING_MODE
          READ_REG_2-VAL
          READ_REG_2
          READ_REG_3-VAL
          READ_REG_3
          READ_REG_4-VAL
          READ_REG_4
          HOUSING_HUMIDITY-VAL
          HOUSING_HUMIDITY
          HOUSING_TEMP-VAL
          HOUSING_TEMP
          ENV_ERR-VAL
          ENV_ERR
          MODE_INDICATOR-VAL
          MODE_INDICATOR
          SYSTEM_VOLTAGE-VAL
          SYSTEM_VOLTAGE
))