// Generated by gencpp from file ds_nav_msgs/RejPolicyCmd.msg
// DO NOT EDIT!


#ifndef DS_NAV_MSGS_MESSAGE_REJPOLICYCMD_H
#define DS_NAV_MSGS_MESSAGE_REJPOLICYCMD_H

#include <ros/service_traits.h>


#include <ds_nav_msgs/RejPolicyCmdRequest.h>
#include <ds_nav_msgs/RejPolicyCmdResponse.h>


namespace ds_nav_msgs
{

struct RejPolicyCmd
{

typedef RejPolicyCmdRequest Request;
typedef RejPolicyCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RejPolicyCmd
} // namespace ds_nav_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ds_nav_msgs::RejPolicyCmd > {
  static const char* value()
  {
    return "bdcc6c6405525471ab73c6f050da9ce0";
  }

  static const char* value(const ::ds_nav_msgs::RejPolicyCmd&) { return value(); }
};

template<>
struct DataType< ::ds_nav_msgs::RejPolicyCmd > {
  static const char* value()
  {
    return "ds_nav_msgs/RejPolicyCmd";
  }

  static const char* value(const ::ds_nav_msgs::RejPolicyCmd&) { return value(); }
};


// service_traits::MD5Sum< ::ds_nav_msgs::RejPolicyCmdRequest> should match
// service_traits::MD5Sum< ::ds_nav_msgs::RejPolicyCmd >
template<>
struct MD5Sum< ::ds_nav_msgs::RejPolicyCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ds_nav_msgs::RejPolicyCmd >::value();
  }
  static const char* value(const ::ds_nav_msgs::RejPolicyCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ds_nav_msgs::RejPolicyCmdRequest> should match
// service_traits::DataType< ::ds_nav_msgs::RejPolicyCmd >
template<>
struct DataType< ::ds_nav_msgs::RejPolicyCmdRequest>
{
  static const char* value()
  {
    return DataType< ::ds_nav_msgs::RejPolicyCmd >::value();
  }
  static const char* value(const ::ds_nav_msgs::RejPolicyCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ds_nav_msgs::RejPolicyCmdResponse> should match
// service_traits::MD5Sum< ::ds_nav_msgs::RejPolicyCmd >
template<>
struct MD5Sum< ::ds_nav_msgs::RejPolicyCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ds_nav_msgs::RejPolicyCmd >::value();
  }
  static const char* value(const ::ds_nav_msgs::RejPolicyCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ds_nav_msgs::RejPolicyCmdResponse> should match
// service_traits::DataType< ::ds_nav_msgs::RejPolicyCmd >
template<>
struct DataType< ::ds_nav_msgs::RejPolicyCmdResponse>
{
  static const char* value()
  {
    return DataType< ::ds_nav_msgs::RejPolicyCmd >::value();
  }
  static const char* value(const ::ds_nav_msgs::RejPolicyCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DS_NAV_MSGS_MESSAGE_REJPOLICYCMD_H
