// Generated by gencpp from file ds_nav_msgs/ZuptCmdResponse.msg
// DO NOT EDIT!


#ifndef DS_NAV_MSGS_MESSAGE_ZUPTCMDRESPONSE_H
#define DS_NAV_MSGS_MESSAGE_ZUPTCMDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ds_nav_msgs
{
template <class ContainerAllocator>
struct ZuptCmdResponse_
{
  typedef ZuptCmdResponse_<ContainerAllocator> Type;

  ZuptCmdResponse_()
    : success(false)  {
    }
  ZuptCmdResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ZuptCmdResponse_

typedef ::ds_nav_msgs::ZuptCmdResponse_<std::allocator<void> > ZuptCmdResponse;

typedef boost::shared_ptr< ::ds_nav_msgs::ZuptCmdResponse > ZuptCmdResponsePtr;
typedef boost::shared_ptr< ::ds_nav_msgs::ZuptCmdResponse const> ZuptCmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator1> & lhs, const ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator1> & lhs, const ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ds_nav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ds_nav_msgs/ZuptCmdResponse";
  }

  static const char* value(const ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool success\n"
"\n"
"\n"
;
  }

  static const char* value(const ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ZuptCmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ds_nav_msgs::ZuptCmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DS_NAV_MSGS_MESSAGE_ZUPTCMDRESPONSE_H
