// Generated by gencpp from file ds_ocomms_msgs/SettingsCmdRequest.msg
// DO NOT EDIT!


#ifndef DS_OCOMMS_MSGS_MESSAGE_SETTINGSCMDREQUEST_H
#define DS_OCOMMS_MSGS_MESSAGE_SETTINGSCMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ds_ocomms_msgs
{
template <class ContainerAllocator>
struct SettingsCmdRequest_
{
  typedef SettingsCmdRequest_<ContainerAllocator> Type;

  SettingsCmdRequest_()
    : PARAM_DESTINATION()
    , PARAM_PAYLOAD()  {
    }
  SettingsCmdRequest_(const ContainerAllocator& _alloc)
    : PARAM_DESTINATION(_alloc)
    , PARAM_PAYLOAD(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _PARAM_DESTINATION_type;
  _PARAM_DESTINATION_type PARAM_DESTINATION;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _PARAM_PAYLOAD_type;
  _PARAM_PAYLOAD_type PARAM_PAYLOAD;





  typedef boost::shared_ptr< ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SettingsCmdRequest_

typedef ::ds_ocomms_msgs::SettingsCmdRequest_<std::allocator<void> > SettingsCmdRequest;

typedef boost::shared_ptr< ::ds_ocomms_msgs::SettingsCmdRequest > SettingsCmdRequestPtr;
typedef boost::shared_ptr< ::ds_ocomms_msgs::SettingsCmdRequest const> SettingsCmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator1> & lhs, const ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.PARAM_DESTINATION == rhs.PARAM_DESTINATION &&
    lhs.PARAM_PAYLOAD == rhs.PARAM_PAYLOAD;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator1> & lhs, const ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ds_ocomms_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0cd996ec874ec1963dc28c60de4aa262";
  }

  static const char* value(const ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0cd996ec874ec196ULL;
  static const uint64_t static_value2 = 0x3dc28c60de4aa262ULL;
};

template<class ContainerAllocator>
struct DataType< ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ds_ocomms_msgs/SettingsCmdRequest";
  }

  static const char* value(const ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string PARAM_DESTINATION\n"
"string PARAM_PAYLOAD\n"
;
  }

  static const char* value(const ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.PARAM_DESTINATION);
      stream.next(m.PARAM_PAYLOAD);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SettingsCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ds_ocomms_msgs::SettingsCmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "PARAM_DESTINATION: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.PARAM_DESTINATION);
    s << indent << "PARAM_PAYLOAD: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.PARAM_PAYLOAD);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DS_OCOMMS_MSGS_MESSAGE_SETTINGSCMDREQUEST_H
