// Generated by gencpp from file ds_hotel_msgs/ClioChgCmdRequest.msg
// DO NOT EDIT!


#ifndef DS_HOTEL_MSGS_MESSAGE_CLIOCHGCMDREQUEST_H
#define DS_HOTEL_MSGS_MESSAGE_CLIOCHGCMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ds_hotel_msgs
{
template <class ContainerAllocator>
struct ClioChgCmdRequest_
{
  typedef ClioChgCmdRequest_<ContainerAllocator> Type;

  ClioChgCmdRequest_()
    : command(0)  {
    }
  ClioChgCmdRequest_(const ContainerAllocator& _alloc)
    : command(0)  {
  (void)_alloc;
    }



   typedef uint8_t _command_type;
  _command_type command;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(CHARGE_CMD_OFF)
  #undef CHARGE_CMD_OFF
#endif
#if defined(_WIN32) && defined(CHARGE_CMD_CHARGE)
  #undef CHARGE_CMD_CHARGE
#endif

  enum {
    CHARGE_CMD_OFF = 1u,
    CHARGE_CMD_CHARGE = 2u,
  };


  typedef boost::shared_ptr< ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ClioChgCmdRequest_

typedef ::ds_hotel_msgs::ClioChgCmdRequest_<std::allocator<void> > ClioChgCmdRequest;

typedef boost::shared_ptr< ::ds_hotel_msgs::ClioChgCmdRequest > ClioChgCmdRequestPtr;
typedef boost::shared_ptr< ::ds_hotel_msgs::ClioChgCmdRequest const> ClioChgCmdRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator1> & lhs, const ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator1> & lhs, const ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ds_hotel_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ed3bb81a1dc90df1ec32880e67a53b5";
  }

  static const char* value(const ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ed3bb81a1dc90dfULL;
  static const uint64_t static_value2 = 0x1ec32880e67a53b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ds_hotel_msgs/ClioChgCmdRequest";
  }

  static const char* value(const ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 CHARGE_CMD_OFF=1\n"
"uint8 CHARGE_CMD_CHARGE=2\n"
"\n"
"uint8 command\n"
;
  }

  static const char* value(const ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClioChgCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ds_hotel_msgs::ClioChgCmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DS_HOTEL_MSGS_MESSAGE_CLIOCHGCMDREQUEST_H
