// Generated by gencpp from file ds_hotel_msgs/PwrSwitchDeviceCmd.msg
// DO NOT EDIT!


#ifndef DS_HOTEL_MSGS_MESSAGE_PWRSWITCHDEVICECMD_H
#define DS_HOTEL_MSGS_MESSAGE_PWRSWITCHDEVICECMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ds_core_msgs/DsHeader.h>

namespace ds_hotel_msgs
{
template <class ContainerAllocator>
struct PwrSwitchDeviceCmd_
{
  typedef PwrSwitchDeviceCmd_<ContainerAllocator> Type;

  PwrSwitchDeviceCmd_()
    : header()
    , ds_header()
    , card()
    , channel()
    , desiredState()  {
    }
  PwrSwitchDeviceCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ds_header(_alloc)
    , card(_alloc)
    , channel(_alloc)
    , desiredState(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::ds_core_msgs::DsHeader_<ContainerAllocator>  _ds_header_type;
  _ds_header_type ds_header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _card_type;
  _card_type card;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _channel_type;
  _channel_type channel;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _desiredState_type;
  _desiredState_type desiredState;





  typedef boost::shared_ptr< ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator> const> ConstPtr;

}; // struct PwrSwitchDeviceCmd_

typedef ::ds_hotel_msgs::PwrSwitchDeviceCmd_<std::allocator<void> > PwrSwitchDeviceCmd;

typedef boost::shared_ptr< ::ds_hotel_msgs::PwrSwitchDeviceCmd > PwrSwitchDeviceCmdPtr;
typedef boost::shared_ptr< ::ds_hotel_msgs::PwrSwitchDeviceCmd const> PwrSwitchDeviceCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator1> & lhs, const ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ds_header == rhs.ds_header &&
    lhs.card == rhs.card &&
    lhs.channel == rhs.channel &&
    lhs.desiredState == rhs.desiredState;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator1> & lhs, const ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ds_hotel_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3410290a421d03145eda197bdf6cc77a";
  }

  static const char* value(const ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3410290a421d0314ULL;
  static const uint64_t static_value2 = 0x5eda197bdf6cc77aULL;
};

template<class ContainerAllocator>
struct DataType< ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ds_hotel_msgs/PwrSwitchDeviceCmd";
  }

  static const char* value(const ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The standard 2-part DsHeader block\n"
"# This allows both a standard ROS header and DS-specific header blocks\n"
"# See HEADERS.md in ds_core_msgs for details\n"
"std_msgs/Header header\n"
"ds_core_msgs/DsHeader ds_header\n"
"\n"
"string card\n"
"string channel\n"
"string desiredState\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ds_core_msgs/DsHeader\n"
"# This is half our standard header for ds_msgs; see\n"
"# HEADERS.md for details\n"
"\n"
"# This header should ALWAYS be paired with a std_msgs/Header\n"
"# and should ALWAYS reference HEADERS.md.  If you're looking at this\n"
"# file to add headers to a type, you probably want to copy/paste\n"
"# the following block:\n"
"#\n"
"#     # The standard 2-part DsHeader block\n"
"#     # This allows both a standard ROS header and DS-specific header blocks\n"
"#     # See HEADERS.md in ds_core_msgs for details\n"
"#     std_msgs/Header header\n"
"#     ds_core_msgs/DsHeader ds_header\n"
"#\n"
"\n"
"# Time data was received or sent out (i/o time)\n"
"time io_time\n"
"\n"
"# Sensor source UUID\n"
"uint8[16] source_uuid\n"
"\n"
;
  }

  static const char* value(const ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ds_header);
      stream.next(m.card);
      stream.next(m.channel);
      stream.next(m.desiredState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PwrSwitchDeviceCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ds_hotel_msgs::PwrSwitchDeviceCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ds_header: ";
    s << std::endl;
    Printer< ::ds_core_msgs::DsHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.ds_header);
    s << indent << "card: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.card);
    s << indent << "channel: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.channel);
    s << indent << "desiredState: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.desiredState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DS_HOTEL_MSGS_MESSAGE_PWRSWITCHDEVICECMD_H
